steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'first_cloud_function'
      - '--entry-point'
      - 'first_cloud_function'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--source'
      - '.'
      - '--region'
      - 'us-west2'
options:
  logging: CLOUD_LOGGING_ONLY

timeout: '540s'
